[[oneAPI_Support]]
arch = "x86_64"
git-tree-sha1 = "157ce8528e169ca1ac5cb50c1fee79495edabeaf"
libc = "glibc"
os = "linux"

    [[oneAPI_Support.download]]
    sha256 = "001a7e680955cf09fda3dc2aece7792cb099e50ce61b959c4a6e13c4417b096a"
    url = "https://github.com/JuliaBinaryWrappers/oneAPI_Support_jll.jl/releases/download/oneAPI_Support-v0.1.0+1/oneAPI_Support.v0.1.0.x86_64-linux-gnu.tar.gz"
