[[oneAPI_Support]]
arch = "x86_64"
git-tree-sha1 = "d31595b2942b280f3811d24d5b4f83207e9b1da8"
libc = "glibc"
os = "linux"

    [[oneAPI_Support.download]]
    sha256 = "7667beb2964019dd7362841cc134576a75c863a648846adfaf7cfd03d44239d0"
    url = "https://github.com/JuliaBinaryWrappers/oneAPI_Support_jll.jl/releases/download/oneAPI_Support-v0.3.0+0/oneAPI_Support.v0.3.0.x86_64-linux-gnu.tar.gz"
