[[oneAPI_Support]]
arch = "x86_64"
git-tree-sha1 = "9ee16b343b9f98a2396dcd835a5203fa30b10f26"
libc = "glibc"
os = "linux"

    [[oneAPI_Support.download]]
    sha256 = "63dbdb65b60bd6c7d76420ea871c466504d45559b2c7309da77d74cd2a05fd8d"
    url = "https://github.com/JuliaBinaryWrappers/oneAPI_Support_jll.jl/releases/download/oneAPI_Support-v0.5.1+0/oneAPI_Support.v0.5.1.x86_64-linux-gnu.tar.gz"
