[[oneAPI_Support]]
arch = "x86_64"
git-tree-sha1 = "71fad0bc5bbbcd047a365ef59b8a727c72a3b549"
libc = "glibc"
os = "linux"

    [[oneAPI_Support.download]]
    sha256 = "2320b6b563f6afc61928fbc1df3f8fd9e4ce17f2a948b1c4725e3417fd8e7737"
    url = "https://github.com/JuliaBinaryWrappers/oneAPI_Support_jll.jl/releases/download/oneAPI_Support-v0.5.0+0/oneAPI_Support.v0.5.0.x86_64-linux-gnu.tar.gz"
