[[oneAPI_Support]]
arch = "x86_64"
git-tree-sha1 = "753951ac72fc744543c454311ad07fb9424d5d78"
libc = "glibc"
os = "linux"

    [[oneAPI_Support.download]]
    sha256 = "dbf1b88ab88fa763ff237f1e08fa980765c81d262919138cfb3baffd13173591"
    url = "https://github.com/JuliaBinaryWrappers/oneAPI_Support_jll.jl/releases/download/oneAPI_Support-v0.8.0+0/oneAPI_Support.v0.8.0.x86_64-linux-gnu.tar.gz"
