[[oneAPI_Support]]
arch = "x86_64"
git-tree-sha1 = "305749e6c396bed3bac62fdcf1d7f5f6d1accf79"
libc = "glibc"
os = "linux"

    [[oneAPI_Support.download]]
    sha256 = "c7e1876a2f062df930e42123ee24d7a0a13276a5b0af1e409bf993b2940554d3"
    url = "https://github.com/JuliaBinaryWrappers/oneAPI_Support_jll.jl/releases/download/oneAPI_Support-v0.3.2+0/oneAPI_Support.v0.3.2.x86_64-linux-gnu.tar.gz"
