[[oneAPI_Support]]
arch = "x86_64"
git-tree-sha1 = "47961d93e8aad63d61f29985ef28a32e319ce757"
libc = "glibc"
os = "linux"

    [[oneAPI_Support.download]]
    sha256 = "96e561867317e6c9a7c6f124b97480238be3b9a7ae369aec9aca6bbfce26a138"
    url = "https://github.com/JuliaBinaryWrappers/oneAPI_Support_jll.jl/releases/download/oneAPI_Support-v0.9.1+0/oneAPI_Support.v0.9.1.x86_64-linux-gnu.tar.gz"
