[[oneAPI_Support]]
arch = "x86_64"
git-tree-sha1 = "092e8d177694c8c95d07259a2c3ab0053d533e1d"
libc = "glibc"
os = "linux"

    [[oneAPI_Support.download]]
    sha256 = "dd52f950ace01c5390ddbfe4263e34051e0c10b76ea5663abfd414944c2b0924"
    url = "https://github.com/JuliaBinaryWrappers/oneAPI_Support_jll.jl/releases/download/oneAPI_Support-v0.1.1+0/oneAPI_Support.v0.1.1.x86_64-linux-gnu.tar.gz"
