[[oneAPI_Support]]
arch = "x86_64"
git-tree-sha1 = "a2db122bef19e3744b447f2d6ab328359909deb9"
libc = "glibc"
os = "linux"

    [[oneAPI_Support.download]]
    sha256 = "dd2eb0870c8ff9bfca33bd15205750552af3054be9f9fbc51120c68878259469"
    url = "https://github.com/JuliaBinaryWrappers/oneAPI_Support_jll.jl/releases/download/oneAPI_Support-v0.2.0+0/oneAPI_Support.v0.2.0.x86_64-linux-gnu.tar.gz"
