[[oneAPI_Support]]
arch = "x86_64"
git-tree-sha1 = "5eb72274d03debeeb85d66cfc81455a55135de46"
libc = "glibc"
os = "linux"

    [[oneAPI_Support.download]]
    sha256 = "fbebfab9670d1deda03ddb075d3a2a624b21fa9dec195aa4307657bd3b10ccfc"
    url = "https://github.com/JuliaBinaryWrappers/oneAPI_Support_jll.jl/releases/download/oneAPI_Support-v0.2.2+0/oneAPI_Support.v0.2.2.x86_64-linux-gnu.tar.gz"
