[[oneAPI_Support]]
arch = "x86_64"
git-tree-sha1 = "7a05361d8a636f5b902d5789e48c7fdf053376b7"
libc = "glibc"
os = "linux"

    [[oneAPI_Support.download]]
    sha256 = "a77bc0d010d376bc722cc00d138488478f3259f10820ae69a2dabb71b0b52aa9"
    url = "https://github.com/JuliaBinaryWrappers/oneAPI_Support_jll.jl/releases/download/oneAPI_Support-v0.6.0+0/oneAPI_Support.v0.6.0.x86_64-linux-gnu.tar.gz"
