# Autogenerated wrapper script for oneAPI_Support_jll for x86_64-linux-gnu
export liboneapi_support

JLLWrappers.@generate_wrapper_header("oneAPI_Support")
JLLWrappers.@declare_library_product(liboneapi_support, "liboneapi_support.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        liboneapi_support,
        "lib/liboneapi_support.so",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
